### ISSUE TITLE
Ranks Issue

### ISSUE THREAD

**Issue by iiDirtblock** [MC-Prison/Prison#81] opened 2018-04-06 17:56 UTC
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Ranks
### Describe the issue you are experiencing.
Ranks isnt enabling. Heres what the console says:
[13:33:50 INFO]: | Prison | Ranks enable start...
[13:33:50 ERROR]: Error occurred while enabling Prison v3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at tech.mcprison.prison.ranks.data.RankPlayer.<init>(RankPlayer.java:64) ~[?:?]
        at tech.mcprison.prison.ranks.managers.PlayerManager.lambda$loadPlayers$0(PlayerManager.java:79) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_161]
        at tech.mcprison.prison.ranks.managers.PlayerManager.loadPlayers(PlayerManager.java:79) ~[?:?]
        at tech.mcprison.prison.ranks.PrisonRanks.enable(PrisonRanks.java:114) ~[?:?]
        at tech.mcprison.prison.modules.ModuleManager.enableModule(ModuleManager.java:83) ~[?:?]
        at tech.mcprison.prison.modules.ModuleManager.registerModule(ModuleManager.java:57) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.initModules(SpigotPrison.java:244) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

### Describe the steps to reproduce the problem.
I restart console but the same thing hapens everytime! do you know why?

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by DylanFPS** [comment] 2018-04-06 19:16
I know exactly what the problem is, will fix it over the weekend

**Comment by iiDirtblock** [comment] 2018-04-06 19:24
Okay.

**Comment by iiDirtblock** [comment] 2018-04-06 19:26
Can you give me some help? or any details regarding this problem?

**Comment by Hxtch2** [comment] 2018-04-06 20:51
okay thanks DylanFPS for coming through to us

**Comment by Hxtch2** [comment] 2018-04-08 12:43
Thanks alot man

**Comment by DylanFPS** [comment] 2018-04-13 13:05
Does this fix actually work, as we're having reports from some users that the plugin instantly disables itself following it being enabled?

**Comment by DylanFPS** [comment] 2018-04-13 13:06
Lol just saw #83. Closing...

**Closed by DylanFPS** 2018-04-13 13:06 UTC

**Comment by Muzzledroom** [comment] 2018-05-16 21:13
@DylanFPS I couldn't help but ask how to download the file. I click on the link aka the "here" link, and I get directed to page not found then to "Build Dashboard" I click on "Prison 3 Nightly" which I am assuming is the most recent build. I click on "#37" But I am completely lost from here. Either I'm completely in the wrong area or I am blind. If i have to create an account to download it, that might also be a problem as the website is super buggy for me.
