### ISSUE TITLE
When you try to install Sane Economy after Prison

### ISSUE THREAD

**Issue by MCTyler** [MC-Prison/Prison#62] opened 2018-01-23 10:13 UTC
[03:42:59 ERROR]: Could not load 'plugins/SaneEconomyCore-0.13.1-SNAPSHOT.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized! at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot.jar:git-Spigot-9b8bba4-bd30843] at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-9b8bba4-bd30843] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-9b8bba4-bd30843] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151] Caused by: java.lang.IllegalArgumentException: Plugin already initialized! at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:183) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.appledash.saneeconomy.shaded.sanelib.SanePlugin.<init>(SanePlugin.java:19) ~[?:?] at org.appledash.saneeconomy.SaneEconomy.<init>(SaneEconomy.java:47) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151] at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151] at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] ... 6 more Caused by: java.lang.IllegalStateException: Initial initialization at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:186) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:60) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at tech.mcprison.prison.spigot.SpigotPrison.<init>(SpigotPrison.java:58) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151] at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151] at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151] at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:90) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] ... 6 more

 @MCTyler

**Comment by DylanFPS** [comment] 2018-01-23 18:15
There is no logical reason why Prison would have anything to do this 🤔

**Comment by MCTyler** [comment] 2018-01-23 19:07
Because you guys have SaneEconomy initializing in Prison Start. If I remove Prison, SaneEconomy works just fine.
PluginClassLoader.java:90) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] ... 6 more Caused by: java.lang.IllegalStateException: Initial initialization at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:186) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at org.bukkit.plugin.java.JavaPlugin.(JavaPlugin.java:60) ~[spigot.jar:git-Spigot-9b8bba4-bd30843] at **tech.mcprison.prison.spigot.SpigotPrison.(SpigotPrison.java:58)** ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151] at

**Comment by MCTyler** [comment] 2018-01-23 19:10
I edited the Prison Repo and took out all references to Essentials and SaneEconomy and it works fine so as far as I'm concerned I fixed it. You can close till someone else has this issue.

**Comment by DylanFPS** [comment] 2018-01-23 19:37
Ah okay. Well considering this *is* a bug, I'll leave it open. Glad you got it fixed.

**Comment by faizaand** [comment] 2018-01-23 22:51
I'm gonna assign this to me and look into this in more detail over the weekend.

**Comment by MCTyler** [comment] 2018-01-24 11:40
Quick ? Sir @faizaand ...Which, if, IDE do you use? I cannot get this repo to load into Eclipse Properly so everything I do I have to edit from command line. I use Linux OS.

**Comment by DylanFPS** [comment] 2018-02-26 12:51
I just installed Sane Economy along with the Prison 3.1 dev build and, I couldn't reproduce this error. Closing this...

**Closed by DylanFPS** 2018-02-26 12:51 UTC
Labels: bug, can't reproduce

**Comment by MCTyler** [comment] 2018-02-26 13:28
Probably Because I use CMI. Good no issue!
