### ISSUE TITLE
Bug on Mines!!!

### ISSUE THREAD

**Issue by selwo** [MC-Prison/Prison#72] opened 2018-02-18 16:06 UTC
Bug report:

Bug on Mines. 

When reboting server all mines change my tree log into Oak. But only if ID is not round number. 
Example: I set my mines into: Oak(id:17), Spruce(id:17:1), Birch(id:17:2), Jungle(id:17:3), Acacia(id:162), Dark Oak(id:162:1). and after playing few hours everything was fine and mines reseted correctly, but when i reloaded my server all mines change every id with **:** with round number id: 17 or id: 162. and it keep doing it every time after reload and i need to set up mines all over again.

I am running 1.12. Version.
Plugin version: Prison 3.0.3

Example what it does in config file:
{"world":"Prison","minY":92.0,"minX":-784.0,"maxZ":-615.0,"maxY":94.0,"blocks":["minecraft:leaves-40.0","minecraft:log-10.0","minecraft:log-10.0","minecraft:log-10.0","minecraft:log-10.0","minecraft:log2-10.0","minecraft:log2-10.0"],"maxX":-775.0,"name":"wooda2","minZ":-591.0,"hasSpawn":false}

I think that problem is with using names insted of block ID's in config file that are created in data storage after making a mine. insted of saying  "blocks":["minecraft:leaves-40.0","miecraft:log-10" it should say like this: "blocks":["minecraft:18-40.0","miecraft:17:1-10","miecraft:17:2-10","miecraft:17:3-10","miecraft:162-10","miecraft:162:1-10"

Where i can find suported block names for Prison plugin?

I might be wrong!! 
Hope it helps finding what's problem with it. 

Keep up with good work. 👍 

Have a nice day!!

**Comment by DylanFPS** [comment] 2018-02-18 21:49
Duplicate of #70

**Closed by DylanFPS** 2018-02-18 21:49 UTC
