### ISSUE TITLE
/ranks doesn't work

### ISSUE THREAD

**Issue by Seff300** [MC-Prison/Prison#84] opened 2018-04-13 11:32 UTC
### Which module are you submitting this issue for?
Ranks

### Describe the issue you are experiencing..
When I do /ranks it tells me Unknown command. Type "/help" for help.
Before I connected it to SQL it worked.

### Describe the steps to reproduce the problem.
Here, you should tell us what we need to know in order to cause the same problem on our machines, so that we may debug it. Please include your Spigot, Prison, and dependency versions. This section is only needed if you are making a bug report.
Connect Prison with SQL
Do /ranks
Prison version is 3.1
Using Spigot 1.12.2

### Anything else we need to know?

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by DylanFPS** [comment] 2018-04-13 13:04
Duplicate of #81

**Closed by DylanFPS** 2018-04-13 13:04 UTC
