### ISSUE TITLE
Mine reset teleportation issues.

### ISSUE THREAD

**Issue by xTomiK101** [MC-Prison/Prison#97] opened 2018-05-31 13:03 UTC
**### Which module are you submitting this issue for?**
Prison 3 Mines Module on a Spigot Server of the latest Minecraft update.

**### Describe the issue you are experiencing.**
When the mines reset the players do not get teleported out to the mine spawn point. They just suffocate in the new blocks placed from when the mine resets. I've had the mine spawn points set up for a few weeks now and they were working perfectly by teleporting players to the mine spawn on reset. However, for the past 3 days (when it was first noticed) they no longer teleport you out when the mine resets, they suffocate you. I have tried resetting the mine spawn point but they still do not teleport you to the mine spawn on mine reset.

**### Describe the steps to reproduce the problem.**
This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The prison version is 3.1.1

**### Anything else we need to know?**
I have multiple other plugins on the server. I can give you the names if you think they may be inflicting with this?

**Comment by DylanFPS** [comment] 2018-05-31 17:45
Duplicate of #82

**Closed by DylanFPS** 2018-05-31 17:45 UTC
