### ISSUE TITLE
Mines reset teleportation

### ISSUE THREAD

**Issue by Hxtch2** [MC-Prison/Prison#85] opened 2018-04-21 02:10 UTC
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Mines

### Describe the issue you are experiencing.
Okay so a few weeks ago i reported an issue where the mine only teleport us on reset from time to time. I came to figure out that it doesn't teleport members at all besides the server operators like the people who have access to the console on server.pro or some other thing idk. I am not sure if there is a specific permission node for players because it wasn't listed in the permissions on spigot.org so please if you may, help us figure this out. Thanks :)

**Comment by DylanFPS** [comment] 2018-04-21 11:12
Duplicate of #82

**Closed by DylanFPS** 2018-04-21 11:12 UTC
